comment: false # Disable the comment that is posted on pull requests.
coverage:
  status:
    patch:
      default:
        only_pulls: true # Only show the `codecov/patch` commit status on pull requests.
    project:
      default:
        only_pulls: true # Only show the `codecov/project` commit status on pull requests.
github_checks:
    annotations: false # Disable the annotations in the "Files Changed" view of a pull request.
