## This file autogenerated by ext/HistoricalStdlibGenerator/generate_historical_stdlibs.jl

# Julia standard libraries with segment-based compression:
# - Each stdlib split into segments where base info (name, uuid, deps, weakdeps) is constant
# - Within each segment, only package version numbers stored per Julia version range

# UUID constants
const ArgTools_uuid = UUID("0dad84c5-d112-42e6-8d28-ef12dabb789f")
const Artifacts_uuid = UUID("56f22d72-fd6d-98f1-02f0-08ddc0907c33")
const Base64_uuid = UUID("2a0f44e3-6c83-55bd-87e4-b1978d98bd5f")
const CRC32c_uuid = UUID("8bf52ea8-c179-5cab-976a-9e18b702a9bc")
const CompilerSupportLibraries_jll_uuid = UUID("e66e0078-7015-5450-92f7-15fbd957f2ae")
const Dates_uuid = UUID("ade2ca70-3891-5945-98fb-dc099432e06a")
const DelimitedFiles_uuid = UUID("8bb1440f-4735-579b-a4ab-409b98df4dab")
const Distributed_uuid = UUID("8ba89e20-285c-5b6f-9357-94700520ee1b")
const Downloads_uuid = UUID("f43a241f-c20a-4ad4-852c-f6b1247861c6")
const FileWatching_uuid = UUID("7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee")
const Future_uuid = UUID("9fa8497b-333b-5362-9e8d-4d0656e87820")
const GMP_jll_uuid = UUID("781609d7-10c4-51f6-84f2-b8444358ff6d")
const InteractiveUtils_uuid = UUID("b77e0a4c-d291-57a0-90e8-8db25a27a240")
const JuliaSyntaxHighlighting_uuid = UUID("ac6e5ff7-fb65-4e79-a425-ec3bc9c03011")
const LLD_jll_uuid = UUID("d55e3150-da41-5e91-b323-ecfd1eec6109")
const LLVMLibUnwind_jll_uuid = UUID("47c5dbc3-30ba-59ef-96a6-123e260183d9")
const LazyArtifacts_uuid = UUID("4af54fe1-eca0-43a8-85a7-787d91b784e3")
const LibCURL_jll_uuid = UUID("deac9b47-8bc7-5906-a0fe-35ac56dc84c0")
const LibCURL_uuid = UUID("b27032c2-a3e7-50c8-80cd-2d36dbcbfd21")
const LibGit2_jll_uuid = UUID("e37daf67-58a4-590a-8e99-b0245dd2ffc5")
const LibGit2_uuid = UUID("76f85450-5226-5b5a-8eaa-529ad045b433")
const LibOSXUnwind_jll_uuid = UUID("a83860b7-747b-57cf-bf1f-3e79990d037f")
const LibSSH2_jll_uuid = UUID("29816b5a-b9ab-546f-933c-edad1886dfa8")
const LibUV_jll_uuid = UUID("183b4373-6708-53ba-ad28-60e28bb38547")
const LibUnwind_jll_uuid = UUID("745a5e78-f969-53e9-954f-d19f2f74f4e3")
const Libdl_uuid = UUID("8f399da3-3557-5675-b5ff-fb832c97cbdb")
const LinearAlgebra_uuid = UUID("37e2e46d-f89d-539d-b4ee-838fcccc9c8e")
const Logging_uuid = UUID("56ddb016-857b-54e1-b83d-db4d58db5568")
const MPFR_jll_uuid = UUID("3a97d323-0669-5f0c-9066-3539efd106a3")
const Markdown_uuid = UUID("d6f4376e-aef5-505a-96c1-9c027394607a")
const MbedTLS_jll_uuid = UUID("c8ffd9c3-330d-5841-b78e-0817d7145fa1")
const Mmap_uuid = UUID("a63ad114-7e13-5084-954f-fe012c677804")
const MozillaCACerts_jll_uuid = UUID("14a3606d-f60d-562e-9121-12d972cd8159")
const NetworkOptions_uuid = UUID("ca575930-c2e3-43a9-ace4-1e988b2c1908")
const OpenBLAS_jll_uuid = UUID("4536629a-c528-5b80-bd46-f80d51c5b363")
const OpenLibm_jll_uuid = UUID("05823500-19ac-5b8b-9628-191a04bc5112")
const OpenSSL_jll_uuid = UUID("458c3c95-2e84-50aa-8efc-19380b2a3a95")
const PCRE2_jll_uuid = UUID("efcefdf7-47ab-520b-bdef-62a2eaa19f15")
const Pkg_uuid = UUID("44cfe95a-1eb2-52ea-b672-e2afdf69b78f")
const Printf_uuid = UUID("de0858da-6303-5e67-8744-51eddeeeb8d7")
const Profile_uuid = UUID("9abbd945-dff8-562f-b5e8-e1ebf5ef1b79")
const REPL_uuid = UUID("3fa0cd96-eef1-5676-8a61-b3b8758bbffb")
const Random_uuid = UUID("9a3f8284-a2c9-5f02-9a11-845980a1fd5c")
const SHA_uuid = UUID("ea8e919c-243c-51af-8825-aaa63cd721ce")
const Serialization_uuid = UUID("9e88b42a-f829-5b0c-bbe9-9e923198166b")
const SharedArrays_uuid = UUID("1a1011a3-84de-559e-8e89-a11a2f7dc383")
const Sockets_uuid = UUID("6462fe0b-24de-5631-8697-dd941f90decc")
const SparseArrays_uuid = UUID("2f01184e-e22b-5df5-ae63-d93ebab69eaf")
const Statistics_uuid = UUID("10745b16-79ce-11e8-11f9-7d13ad32a3b2")
const StyledStrings_uuid = UUID("f489334b-da3d-4c2e-b8f0-e476e12c162b")
const SuiteSparse_jll_uuid = UUID("bea87d4a-7f5b-5778-9afe-8cc45184846c")
const SuiteSparse_uuid = UUID("4607b0f0-06f3-5cda-b6b1-a6196a1729e9")
const TOML_uuid = UUID("fa267f1f-6049-4f14-aa54-33bafae1ed76")
const Tar_uuid = UUID("a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e")
const Test_uuid = UUID("8dfed614-e22c-5e08-85e1-65c5234f0b40")
const UUIDs_uuid = UUID("cf7118a7-6976-5b1a-9a39-7adc72f591a4")
const Unicode_uuid = UUID("4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5")
const Zlib_jll_uuid = UUID("83775a58-1f1d-513f-b197-d71354ab007a")
const Zstd_jll_uuid = UUID("3161d3a3-bdf6-5164-811a-617609db77b4")
const dSFMT_jll_uuid = UUID("05ff407c-b0c1-5878-9df8-858cc2e60c36")
const libLLVM_jll_uuid = UUID("8f36deef-c2a5-5394-99ed-8e07531fb29a")
const libblastrampoline_jll_uuid = UUID("8e850b90-86db-534c-a0d3-1478176c7d93")
const nghttp2_jll_uuid = UUID("8e850ede-7688-5339-a07c-302acd2aaf8d")
const p7zip_jll_uuid = UUID("3f19e933-33d8-53b3-aaab-bd5110c3b7a0")

# Format: UUID => [StdlibSegment(...), ...]
const STDLIB_SEGMENTS = Dict{UUID, Vector{StdlibSegment}}(
    ArgTools_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "ArgTools", uuid = ArgTools_uuid),
            version_ranges = [
                (v"1.6.0", v"1.10.10") => v"1.1.1",
                (v"1.11.0", v"1.14.0") => v"1.1.2",
            ],
        ),
    ],
    Artifacts_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Artifacts", uuid = Artifacts_uuid),
            version_ranges = [
                (v"1.6.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    Base64_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Base64", uuid = Base64_uuid),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    CRC32c_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "CRC32c", uuid = CRC32c_uuid),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    CompilerSupportLibraries_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "CompilerSupportLibraries_jll", uuid = CompilerSupportLibraries_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.2") => v"0.3.6+1",
                (v"1.6.3", v"1.7.1") => v"0.5.0+0",
                (v"1.7.3", v"1.8.2") => v"0.5.2+0",
                (v"1.8.4", v"1.8.4") => v"1.0.1+0",
                (v"1.9.0", v"1.9.1") => v"1.0.2+0",
                (v"1.9.2", v"1.9.4") => v"1.0.5+0",
                (v"1.10.0", v"1.10.0") => v"1.0.5+1",
                (v"1.10.1", v"1.10.1") => v"1.1.0+0",
                (v"1.10.3", v"1.11.5") => v"1.1.1+0",
                (v"1.12.0", v"1.14.0") => v"1.3.0+1",
            ],
        ),
    ],
    Dates_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Dates", uuid = Dates_uuid, deps = UUID[Printf_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    DelimitedFiles_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "DelimitedFiles", uuid = DelimitedFiles_uuid, deps = UUID[Mmap_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.8.4") => nothing,
            ],
        ),
    ],
    Distributed_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Distributed", uuid = Distributed_uuid, deps = UUID[LinearAlgebra_uuid, Sockets_uuid, Random_uuid, Serialization_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.0.4") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Distributed", uuid = Distributed_uuid, deps = UUID[Sockets_uuid, Random_uuid, Serialization_uuid]),
            version_ranges = [
                (v"1.1.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    Downloads_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Downloads", uuid = Downloads_uuid, deps = UUID[ArgTools_uuid, LibCURL_uuid, NetworkOptions_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.1") => v"1.4.0",
                (v"1.6.2", v"1.6.3") => v"1.4.2",
                (v"1.6.4", v"1.6.7") => v"1.4.3",
                (v"1.7.0", v"1.7.1") => v"1.5.2",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Downloads", uuid = Downloads_uuid, deps = UUID[ArgTools_uuid, FileWatching_uuid, LibCURL_uuid, NetworkOptions_uuid]),
            version_ranges = [
                (v"1.7.3", v"1.7.3") => v"1.5.3",
                (v"1.8.0", v"1.12.1") => v"1.6.0",
                (v"1.13.0", v"1.14.0") => v"1.7.0",
            ],
        ),
    ],
    FileWatching_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "FileWatching", uuid = FileWatching_uuid),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    Future_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Future", uuid = Future_uuid, deps = UUID[Random_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    GMP_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "GMP_jll", uuid = GMP_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.6") => v"6.2.0+5",
                (v"1.6.7", v"1.6.7") => v"6.2.1+2",
                (v"1.7.0", v"1.7.3") => v"6.2.1+1",
                (v"1.8.0", v"1.9.4") => v"6.2.1+2",
                (v"1.10.0", v"1.10.10") => v"6.2.1+6",
                (v"1.11.0", v"1.11.5") => v"6.3.0+0",
                (v"1.12.0", v"1.12.1") => v"6.3.0+2",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "GMP_jll", uuid = GMP_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"6.3.0+2",
            ],
        ),
    ],
    InteractiveUtils_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "InteractiveUtils", uuid = InteractiveUtils_uuid, deps = UUID[LinearAlgebra_uuid, Markdown_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.0.4") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "InteractiveUtils", uuid = InteractiveUtils_uuid, deps = UUID[Markdown_uuid]),
            version_ranges = [
                (v"1.1.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    JuliaSyntaxHighlighting_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "JuliaSyntaxHighlighting", uuid = JuliaSyntaxHighlighting_uuid, deps = UUID[StyledStrings_uuid]),
            version_ranges = [
                (v"1.12.0", v"1.14.0") => v"1.12.0",
            ],
        ),
    ],
    LLD_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LLD_jll", uuid = LLD_jll_uuid, deps = UUID[Pkg_uuid, Artifacts_uuid, Zlib_jll_uuid, libLLVM_jll_uuid, Libdl_uuid, TOML_uuid]),
            version_ranges = [
                (v"1.9.0", v"1.9.4") => v"14.0.6+3",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LLD_jll", uuid = LLD_jll_uuid, deps = UUID[Artifacts_uuid, Zlib_jll_uuid, libLLVM_jll_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.10.0", v"1.10.10") => v"15.0.7+10",
                (v"1.11.0", v"1.11.4") => v"16.0.6+4",
                (v"1.11.5", v"1.11.5") => v"16.0.6+5",
                (v"1.12.0", v"1.12.1") => v"18.1.7+5",
                (v"1.13.0", v"1.14.0") => v"20.1.8+0",
            ],
        ),
    ],
    LLVMLibUnwind_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LLVMLibUnwind_jll", uuid = LLVMLibUnwind_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.7.0", v"1.7.3") => v"11.0.1+1",
                (v"1.8.0", v"1.11.5") => v"12.0.1+0",
                (v"1.12.0", v"1.14.0") => v"19.1.4+0",
            ],
        ),
    ],
    LazyArtifacts_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LazyArtifacts", uuid = LazyArtifacts_uuid, deps = UUID[Pkg_uuid, Artifacts_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    LibCURL_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibCURL", uuid = LibCURL_uuid, deps = UUID[MozillaCACerts_jll_uuid, LibCURL_jll_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.7.3") => v"0.6.2",
                (v"1.8.0", v"1.9.2") => v"0.6.3",
                (v"1.9.4", v"1.12.1") => v"0.6.4",
                (v"1.13.0", v"1.14.0") => v"1.0.0",
            ],
        ),
    ],
    LibCURL_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibCURL_jll", uuid = LibCURL_jll_uuid, deps = UUID[LibSSH2_jll_uuid, Artifacts_uuid, Zlib_jll_uuid, nghttp2_jll_uuid, Libdl_uuid, MbedTLS_jll_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.7") => v"7.73.0+3",
                (v"1.7.0", v"1.7.3") => v"7.73.0+4",
                (v"1.8.0", v"1.9.2") => v"7.84.0+0",
                (v"1.9.4", v"1.10.10") => v"8.4.0+0",
                (v"1.11.0", v"1.11.5") => v"8.6.0+0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibCURL_jll", uuid = LibCURL_jll_uuid, deps = UUID[LibSSH2_jll_uuid, OpenSSL_jll_uuid, Artifacts_uuid, Zlib_jll_uuid, nghttp2_jll_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.12.0", v"1.12.1") => v"8.11.1+1",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibCURL_jll", uuid = LibCURL_jll_uuid, deps = UUID[LibSSH2_jll_uuid, Zstd_jll_uuid, OpenSSL_jll_uuid, Artifacts_uuid, Zlib_jll_uuid, nghttp2_jll_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"8.16.0+0",
            ],
        ),
    ],
    LibGit2_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibGit2", uuid = LibGit2_uuid),
            version_ranges = [
                (v"1.0.0", v"1.3.1") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibGit2", uuid = LibGit2_uuid, deps = UUID[Printf_uuid]),
            version_ranges = [
                (v"1.4.0", v"1.5.3") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibGit2", uuid = LibGit2_uuid, deps = UUID[Base64_uuid, NetworkOptions_uuid, Printf_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.9.4") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibGit2", uuid = LibGit2_uuid, deps = UUID[Base64_uuid, NetworkOptions_uuid, Printf_uuid, LibGit2_jll_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.10.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.11.5") => v"1.11.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibGit2", uuid = LibGit2_uuid, deps = UUID[NetworkOptions_uuid, Printf_uuid, LibGit2_jll_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.12.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    LibGit2_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibGit2_jll", uuid = LibGit2_jll_uuid, deps = UUID[LibSSH2_jll_uuid, Artifacts_uuid, Libdl_uuid, MbedTLS_jll_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.7.3") => v"1.2.3+0",
                (v"1.8.0", v"1.8.4") => v"1.3.0+0",
                (v"1.9.0", v"1.9.4") => v"1.5.0+1",
                (v"1.10.0", v"1.10.10") => v"1.6.4+0",
                (v"1.11.0", v"1.11.5") => v"1.7.2+0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibGit2_jll", uuid = LibGit2_jll_uuid, deps = UUID[LibSSH2_jll_uuid, OpenSSL_jll_uuid, Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.12.0", v"1.12.1") => v"1.9.0+0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibGit2_jll", uuid = LibGit2_jll_uuid, deps = UUID[LibSSH2_jll_uuid, OpenSSL_jll_uuid, Artifacts_uuid, Zlib_jll_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid, PCRE2_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"1.9.1+0",
            ],
        ),
    ],
    LibOSXUnwind_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibOSXUnwind_jll", uuid = LibOSXUnwind_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.7") => v"0.0.6+1",
            ],
        ),
    ],
    LibSSH2_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibSSH2_jll", uuid = LibSSH2_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid, MbedTLS_jll_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.7") => v"1.9.1+0",
                (v"1.7.0", v"1.7.3") => v"1.9.1+2",
                (v"1.8.0", v"1.9.2") => v"1.10.2+0",
                (v"1.9.4", v"1.11.5") => v"1.11.0+1",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibSSH2_jll", uuid = LibSSH2_jll_uuid, deps = UUID[OpenSSL_jll_uuid, Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.12.0", v"1.12.1") => v"1.11.3+1",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibSSH2_jll", uuid = LibSSH2_jll_uuid, deps = UUID[OpenSSL_jll_uuid, Artifacts_uuid, Zlib_jll_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"1.11.3+1",
            ],
        ),
    ],
    LibUV_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibUV_jll", uuid = LibUV_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.3") => v"2.0.1+1",
                (v"1.6.4", v"1.6.4") => v"2.0.1+4",
                (v"1.6.5", v"1.8.0") => v"2.0.1+5",
                (v"1.8.2", v"1.8.4") => v"2.0.1+11",
                (v"1.9.0", v"1.9.4") => v"2.0.1+13",
                (v"1.10.0", v"1.10.10") => v"2.0.1+14",
                (v"1.11.0", v"1.11.5") => v"2.0.1+16",
                (v"1.12.0", v"1.12.1") => v"2.0.1+20",
                (v"1.13.0", v"1.14.0") => v"2.0.1+21",
            ],
        ),
    ],
    LibUnwind_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibUnwind_jll", uuid = LibUnwind_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.7.3") => v"1.3.2+0",
                (v"1.8.0", v"1.8.4") => v"1.5.0+0",
                (v"1.9.0", v"1.9.4") => v"1.5.0+4",
                (v"1.10.0", v"1.10.10") => v"1.5.0+5",
                (v"1.11.0", v"1.11.5") => v"1.7.2+2",
                (v"1.12.0", v"1.12.1") => v"1.8.1+2",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LibUnwind_jll", uuid = LibUnwind_jll_uuid, deps = UUID[Artifacts_uuid, Zlib_jll_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"1.8.3+0",
            ],
        ),
    ],
    Libdl_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Libdl", uuid = Libdl_uuid),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    LinearAlgebra_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LinearAlgebra", uuid = LinearAlgebra_uuid, deps = UUID[Libdl_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.6.7") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LinearAlgebra", uuid = LinearAlgebra_uuid, deps = UUID[libblastrampoline_jll_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.7.0", v"1.8.4") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "LinearAlgebra", uuid = LinearAlgebra_uuid, deps = UUID[OpenBLAS_jll_uuid, libblastrampoline_jll_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.9.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.11.5") => v"1.11.0",
                (v"1.12.0", v"1.12.1") => v"1.12.0",
                (v"1.13.0", v"1.14.0") => v"1.13.0",
            ],
        ),
    ],
    Logging_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Logging", uuid = Logging_uuid),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    MPFR_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "MPFR_jll", uuid = MPFR_jll_uuid, deps = UUID[Artifacts_uuid, GMP_jll_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.7") => v"4.1.1+0",
                (v"1.7.0", v"1.8.4") => v"4.1.1+1",
                (v"1.9.0", v"1.9.4") => v"4.1.1+4",
                (v"1.10.0", v"1.10.10") => v"4.2.0+1",
                (v"1.11.0", v"1.11.5") => v"4.2.1+0",
                (v"1.12.0", v"1.12.1") => v"4.2.2+0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "MPFR_jll", uuid = MPFR_jll_uuid, deps = UUID[Artifacts_uuid, GMP_jll_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"4.2.2+0",
            ],
        ),
    ],
    Markdown_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Markdown", uuid = Markdown_uuid, deps = UUID[Base64_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.11.5") => v"1.11.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Markdown", uuid = Markdown_uuid, deps = UUID[Base64_uuid, JuliaSyntaxHighlighting_uuid, StyledStrings_uuid]),
            version_ranges = [
                (v"1.12.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    MbedTLS_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "MbedTLS_jll", uuid = MbedTLS_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.6") => v"2.24.0+1",
                (v"1.6.7", v"1.6.7") => v"2.24.0+4",
                (v"1.7.0", v"1.7.3") => v"2.24.0+2",
                (v"1.8.0", v"1.8.4") => v"2.28.0+0",
                (v"1.9.0", v"1.9.4") => v"2.28.2+0",
                (v"1.10.0", v"1.10.10") => v"2.28.2+1",
                (v"1.11.0", v"1.11.5") => v"2.28.6+0",
            ],
        ),
    ],
    Mmap_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Mmap", uuid = Mmap_uuid),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    MozillaCACerts_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "MozillaCACerts_jll", uuid = MozillaCACerts_jll_uuid),
            version_ranges = [
                (v"1.6.0", v"1.7.3") => v"2020.7.22",
                (v"1.8.0", v"1.8.4") => v"2022.2.1",
                (v"1.9.0", v"1.9.4") => v"2022.10.11",
                (v"1.10.0", v"1.10.10") => v"2023.1.10",
                (v"1.11.0", v"1.11.5") => v"2023.12.12",
                (v"1.12.0", v"1.12.1") => v"2025.5.20",
                (v"1.13.0", v"1.14.0") => v"2025.9.9",
            ],
        ),
    ],
    NetworkOptions_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "NetworkOptions", uuid = NetworkOptions_uuid),
            version_ranges = [
                (v"1.6.0", v"1.11.5") => v"1.2.0",
                (v"1.12.0", v"1.14.0") => v"1.3.0",
            ],
        ),
    ],
    OpenBLAS_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "OpenBLAS_jll", uuid = OpenBLAS_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.3") => v"0.3.10+3",
                (v"1.6.4", v"1.6.4") => v"0.3.10+9",
                (v"1.6.5", v"1.6.7") => v"0.3.10+10",
                (v"1.7.0", v"1.7.0") => v"0.3.13+9",
                (v"1.7.1", v"1.7.3") => v"0.3.13+11",
                (v"1.8.0", v"1.8.4") => v"0.3.20+0",
                (v"1.9.0", v"1.9.4") => v"0.3.21+4",
                (v"1.10.0", v"1.10.0") => v"0.3.23+2",
                (v"1.10.1", v"1.10.10") => v"0.3.23+4",
                (v"1.11.0", v"1.11.5") => v"0.3.27+1",
                (v"1.12.0", v"1.14.0") => v"0.3.29+0",
            ],
        ),
    ],
    OpenLibm_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "OpenLibm_jll", uuid = OpenLibm_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.7") => v"0.7.4+0",
                (v"1.7.0", v"1.7.3") => v"0.7.5+0",
                (v"1.8.0", v"1.9.4") => v"0.8.1+0",
                (v"1.10.0", v"1.10.5") => v"0.8.1+2",
                (v"1.10.9", v"1.10.9") => v"0.8.1+4",
                (v"1.10.10", v"1.10.10") => v"0.8.5+0",
                (v"1.11.0", v"1.11.0") => v"0.8.1+2",
                (v"1.11.4", v"1.11.4") => v"0.8.1+4",
                (v"1.11.5", v"1.11.5") => v"0.8.5+0",
                (v"1.12.0", v"1.12.1") => v"0.8.7+0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "OpenLibm_jll", uuid = OpenLibm_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"0.8.7+0",
            ],
        ),
    ],
    OpenSSL_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "OpenSSL_jll", uuid = OpenSSL_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.12.0", v"1.12.1") => v"3.5.1+0",
                (v"1.13.0", v"1.14.0") => v"3.5.4+0",
            ],
        ),
    ],
    PCRE2_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "PCRE2_jll", uuid = PCRE2_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.0") => v"10.35.0+0",
                (v"1.6.1", v"1.6.6") => v"10.36.0+0",
                (v"1.6.7", v"1.6.7") => v"10.40.0+0",
                (v"1.7.0", v"1.7.3") => v"10.36.0+2",
                (v"1.8.0", v"1.8.4") => v"10.40.0+0",
                (v"1.9.0", v"1.9.4") => v"10.42.0+0",
                (v"1.10.0", v"1.11.5") => v"10.42.0+1",
                (v"1.12.0", v"1.12.1") => v"10.44.0+1",
                (v"1.13.0", v"1.14.0") => v"10.46.0+0",
            ],
        ),
    ],
    Pkg_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Pkg", uuid = Pkg_uuid, deps = UUID[REPL_uuid, LibGit2_uuid, Random_uuid, Dates_uuid, UUIDs_uuid, Markdown_uuid, Printf_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.0.0") => nothing,
                (v"1.0.2", v"1.0.2") => v"1.0.2",
                (v"1.0.3", v"1.0.3") => v"1.0.3",
                (v"1.0.4", v"1.0.4") => v"1.0.4",
                (v"1.1.0", v"1.1.0") => v"1.1.2",
                (v"1.1.1", v"1.1.1") => v"1.1.3",
                (v"1.2.0", v"1.2.0") => v"1.2.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Pkg", uuid = Pkg_uuid, deps = UUID[REPL_uuid, Logging_uuid, LibGit2_uuid, Libdl_uuid, Random_uuid, Dates_uuid, UUIDs_uuid, Markdown_uuid, Printf_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.3.0", v"1.3.0") => v"1.3.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Pkg", uuid = Pkg_uuid, deps = UUID[REPL_uuid, Logging_uuid, LibGit2_uuid, Test_uuid, Libdl_uuid, Random_uuid, Dates_uuid, UUIDs_uuid, Markdown_uuid, Printf_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.3.1", v"1.3.1") => v"1.3.1",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Pkg", uuid = Pkg_uuid, deps = UUID[REPL_uuid, Logging_uuid, LibGit2_uuid, Libdl_uuid, Random_uuid, Dates_uuid, UUIDs_uuid, Markdown_uuid, Printf_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.4.0", v"1.4.0") => v"1.4.0",
                (v"1.5.0", v"1.5.0") => v"1.5.0",
                (v"1.5.3", v"1.5.3") => v"1.5.3",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Pkg", uuid = Pkg_uuid, deps = UUID[p7zip_jll_uuid, REPL_uuid, Logging_uuid, Artifacts_uuid, LibGit2_uuid, Libdl_uuid, Random_uuid, Serialization_uuid, Tar_uuid, Dates_uuid, UUIDs_uuid, Markdown_uuid, Printf_uuid, SHA_uuid, Downloads_uuid, TOML_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.1") => v"1.5.0",
                (v"1.6.2", v"1.6.5") => v"1.6.2",
                (v"1.6.6", v"1.6.6") => v"1.6.6",
                (v"1.6.7", v"1.6.7") => v"1.6.7",
                (v"1.7.0", v"1.7.3") => v"1.7.0",
                (v"1.8.0", v"1.8.4") => v"1.8.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Pkg", uuid = Pkg_uuid, deps = UUID[p7zip_jll_uuid, REPL_uuid, Logging_uuid, Artifacts_uuid, LibGit2_uuid, FileWatching_uuid, Libdl_uuid, Random_uuid, Serialization_uuid, Tar_uuid, Dates_uuid, UUIDs_uuid, Markdown_uuid, Printf_uuid, SHA_uuid, Downloads_uuid, TOML_uuid]),
            version_ranges = [
                (v"1.9.0", v"1.9.1") => v"1.9.0",
                (v"1.9.2", v"1.9.4") => v"1.9.2",
                (v"1.10.0", v"1.10.10") => v"1.10.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Pkg", uuid = Pkg_uuid, deps = UUID[p7zip_jll_uuid, Logging_uuid, Artifacts_uuid, LibGit2_uuid, FileWatching_uuid, Libdl_uuid, Random_uuid, Tar_uuid, Dates_uuid, UUIDs_uuid, Markdown_uuid, Printf_uuid, SHA_uuid, Downloads_uuid, TOML_uuid], weakdeps = UUID[REPL_uuid]),
            version_ranges = [
                (v"1.11.0", v"1.11.5") => v"1.11.0",
                (v"1.12.0", v"1.12.1") => v"1.12.0",
                (v"1.13.0", v"1.13.0") => v"1.13.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Pkg", uuid = Pkg_uuid, deps = UUID[Zstd_jll_uuid, p7zip_jll_uuid, Logging_uuid, Artifacts_uuid, LibGit2_uuid, FileWatching_uuid, Libdl_uuid, Random_uuid, Tar_uuid, Dates_uuid, UUIDs_uuid, Markdown_uuid, Printf_uuid, SHA_uuid, Downloads_uuid, TOML_uuid], weakdeps = UUID[REPL_uuid]),
            version_ranges = [
                (v"1.14.0", v"1.14.0") => v"1.13.0",
            ],
        ),
    ],
    Printf_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Printf", uuid = Printf_uuid, deps = UUID[Unicode_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    Profile_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Profile", uuid = Profile_uuid, deps = UUID[Printf_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Profile", uuid = Profile_uuid),
            version_ranges = [
                (v"1.11.0", v"1.11.5") => v"1.11.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Profile", uuid = Profile_uuid, deps = UUID[StyledStrings_uuid]),
            version_ranges = [
                (v"1.12.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    REPL_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "REPL", uuid = REPL_uuid, deps = UUID[Sockets_uuid, InteractiveUtils_uuid, Markdown_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.5.3") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "REPL", uuid = REPL_uuid, deps = UUID[Unicode_uuid, Sockets_uuid, InteractiveUtils_uuid, Markdown_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.10.10") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "REPL", uuid = REPL_uuid, deps = UUID[Unicode_uuid, Sockets_uuid, InteractiveUtils_uuid, Markdown_uuid, StyledStrings_uuid]),
            version_ranges = [
                (v"1.11.0", v"1.11.5") => v"1.11.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "REPL", uuid = REPL_uuid, deps = UUID[Unicode_uuid, Sockets_uuid, JuliaSyntaxHighlighting_uuid, InteractiveUtils_uuid, Markdown_uuid, StyledStrings_uuid]),
            version_ranges = [
                (v"1.12.0", v"1.12.1") => v"1.11.0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "REPL", uuid = REPL_uuid, deps = UUID[Unicode_uuid, Sockets_uuid, FileWatching_uuid, JuliaSyntaxHighlighting_uuid, Dates_uuid, InteractiveUtils_uuid, Markdown_uuid, StyledStrings_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    Random_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Random", uuid = Random_uuid, deps = UUID[Serialization_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.6.7") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Random", uuid = Random_uuid, deps = UUID[Serialization_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.7.0", v"1.9.4") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Random", uuid = Random_uuid, deps = UUID[SHA_uuid]),
            version_ranges = [
                (v"1.10.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    SHA_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SHA", uuid = SHA_uuid),
            version_ranges = [
                (v"1.0.0", v"1.7.3") => nothing,
                (v"1.8.0", v"1.12.1") => v"0.7.0",
                (v"1.13.0", v"1.14.0") => v"1.0.0",
            ],
        ),
    ],
    Serialization_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Serialization", uuid = Serialization_uuid),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    SharedArrays_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SharedArrays", uuid = SharedArrays_uuid, deps = UUID[Distributed_uuid, Random_uuid, Serialization_uuid, Mmap_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    Sockets_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Sockets", uuid = Sockets_uuid),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    SparseArrays_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SparseArrays", uuid = SparseArrays_uuid, deps = UUID[LinearAlgebra_uuid, Random_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.8.4") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SparseArrays", uuid = SparseArrays_uuid, deps = UUID[LinearAlgebra_uuid, Libdl_uuid, Random_uuid, Serialization_uuid, SuiteSparse_jll_uuid]),
            version_ranges = [
                (v"1.9.0", v"1.9.4") => nothing,
                (v"1.10.0", v"1.10.10") => v"1.10.0",
                (v"1.11.0", v"1.11.5") => v"1.11.0",
                (v"1.12.0", v"1.12.1") => v"1.12.0",
                (v"1.13.0", v"1.14.0") => v"1.13.0",
            ],
        ),
    ],
    Statistics_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Statistics", uuid = Statistics_uuid, deps = UUID[SparseArrays_uuid, LinearAlgebra_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.8.4") => nothing,
                (v"1.9.0", v"1.9.4") => v"1.9.0",
                (v"1.10.0", v"1.10.10") => v"1.10.0",
            ],
        ),
    ],
    StyledStrings_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "StyledStrings", uuid = StyledStrings_uuid),
            version_ranges = [
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    SuiteSparse_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SuiteSparse", uuid = SuiteSparse_uuid, deps = UUID[SparseArrays_uuid, LinearAlgebra_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.0.3") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SuiteSparse", uuid = SuiteSparse_uuid, deps = UUID[SparseArrays_uuid, LinearAlgebra_uuid, Libdl_uuid, Serialization_uuid]),
            version_ranges = [
                (v"1.0.4", v"1.0.4") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SuiteSparse", uuid = SuiteSparse_uuid, deps = UUID[SparseArrays_uuid, LinearAlgebra_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.1.0", v"1.1.1") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SuiteSparse", uuid = SuiteSparse_uuid, deps = UUID[SparseArrays_uuid, LinearAlgebra_uuid, Libdl_uuid, Serialization_uuid]),
            version_ranges = [
                (v"1.2.0", v"1.14.0") => nothing,
            ],
        ),
    ],
    SuiteSparse_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SuiteSparse_jll", uuid = SuiteSparse_jll_uuid, deps = UUID[OpenBLAS_jll_uuid, Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.7") => v"5.4.1+1",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SuiteSparse_jll", uuid = SuiteSparse_jll_uuid, deps = UUID[Pkg_uuid, Artifacts_uuid, libblastrampoline_jll_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.7.0", v"1.8.4") => v"5.10.1+0",
                (v"1.9.0", v"1.9.4") => v"5.10.1+6",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SuiteSparse_jll", uuid = SuiteSparse_jll_uuid, deps = UUID[Artifacts_uuid, libblastrampoline_jll_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.10.0", v"1.10.10") => v"7.2.1+1",
                (v"1.11.0", v"1.11.5") => v"7.7.0+0",
                (v"1.12.0", v"1.12.1") => v"7.8.3+2",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "SuiteSparse_jll", uuid = SuiteSparse_jll_uuid, deps = UUID[Artifacts_uuid, libblastrampoline_jll_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"7.10.1+0",
            ],
        ),
    ],
    TOML_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "TOML", uuid = TOML_uuid, deps = UUID[Dates_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.8.4") => v"1.0.0",
                (v"1.9.0", v"1.14.0") => v"1.0.3",
            ],
        ),
    ],
    Tar_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Tar", uuid = Tar_uuid, deps = UUID[ArgTools_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.0") => v"1.9.0",
                (v"1.6.1", v"1.6.1") => v"1.9.1",
                (v"1.6.2", v"1.6.7") => v"1.9.3",
                (v"1.7.0", v"1.8.0") => v"1.10.0",
                (v"1.8.2", v"1.8.4") => v"1.10.1",
                (v"1.9.0", v"1.14.0") => v"1.10.0",
            ],
        ),
    ],
    Test_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Test", uuid = Test_uuid, deps = UUID[Logging_uuid, Distributed_uuid, Random_uuid, InteractiveUtils_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.5.3") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Test", uuid = Test_uuid, deps = UUID[Logging_uuid, Random_uuid, Serialization_uuid, InteractiveUtils_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    UUIDs_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "UUIDs", uuid = UUIDs_uuid, deps = UUID[Random_uuid]),
            version_ranges = [
                (v"1.0.0", v"1.0.4") => nothing,
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "UUIDs", uuid = UUIDs_uuid, deps = UUID[Random_uuid, SHA_uuid]),
            version_ranges = [
                (v"1.1.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    Unicode_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Unicode", uuid = Unicode_uuid),
            version_ranges = [
                (v"1.0.0", v"1.10.10") => nothing,
                (v"1.11.0", v"1.14.0") => v"1.11.0",
            ],
        ),
    ],
    Zlib_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Zlib_jll", uuid = Zlib_jll_uuid, deps = UUID[Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.6") => v"1.2.12+0",
                (v"1.6.7", v"1.6.7") => v"1.2.12+3",
                (v"1.7.0", v"1.7.1") => v"1.2.12+1",
                (v"1.7.3", v"1.8.4") => v"1.2.12+3",
                (v"1.9.0", v"1.9.4") => v"1.2.13+0",
                (v"1.10.0", v"1.11.5") => v"1.2.13+1",
                (v"1.12.0", v"1.14.0") => v"1.3.1+2",
            ],
        ),
    ],
    Zstd_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "Zstd_jll", uuid = Zstd_jll_uuid, deps = UUID[Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"1.5.7+1",
            ],
        ),
    ],
    dSFMT_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "dSFMT_jll", uuid = dSFMT_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.7") => v"2.2.4+0",
                (v"1.7.0", v"1.9.4") => v"2.2.4+1",
                (v"1.10.0", v"1.10.10") => v"2.2.4+4",
                (v"1.11.0", v"1.11.5") => v"2.2.5+0",
                (v"1.12.0", v"1.14.0") => v"2.2.5+2",
            ],
        ),
    ],
    libLLVM_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "libLLVM_jll", uuid = libLLVM_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.0") => v"11.0.1+2",
                (v"1.6.1", v"1.6.7") => v"11.0.1+3",
                (v"1.7.0", v"1.7.3") => v"12.0.1+4",
                (v"1.8.0", v"1.8.4") => v"13.0.1+3",
                (v"1.9.0", v"1.9.4") => v"14.0.6+3",
                (v"1.10.0", v"1.10.10") => v"15.0.7+10",
                (v"1.11.0", v"1.11.4") => v"16.0.6+4",
                (v"1.11.5", v"1.11.5") => v"16.0.6+5",
                (v"1.12.0", v"1.12.1") => v"18.1.7+5",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "libLLVM_jll", uuid = libLLVM_jll_uuid, deps = UUID[Zstd_jll_uuid, Artifacts_uuid, Zlib_jll_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"20.1.8+0",
            ],
        ),
    ],
    libblastrampoline_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "libblastrampoline_jll", uuid = libblastrampoline_jll_uuid, deps = UUID[OpenBLAS_jll_uuid, Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.7.0", v"1.7.3") => v"3.0.4+0",
                (v"1.8.0", v"1.8.4") => v"5.1.1+0",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "libblastrampoline_jll", uuid = libblastrampoline_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.9.0", v"1.9.0") => v"5.7.0+0",
                (v"1.9.1", v"1.9.4") => v"5.8.0+0",
                (v"1.10.0", v"1.10.3") => v"5.8.0+1",
                (v"1.10.5", v"1.11.5") => v"5.11.0+0",
                (v"1.12.0", v"1.12.0") => v"5.13.1+1",
                (v"1.12.1", v"1.14.0") => v"5.15.0+0",
            ],
        ),
    ],
    nghttp2_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "nghttp2_jll", uuid = nghttp2_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.7") => v"1.41.0+0",
                (v"1.7.0", v"1.7.3") => v"1.41.0+1",
                (v"1.8.0", v"1.9.2") => v"1.48.0+0",
                (v"1.9.4", v"1.10.10") => v"1.52.0+1",
                (v"1.11.0", v"1.11.5") => v"1.59.0+0",
                (v"1.12.0", v"1.12.1") => v"1.64.0+1",
            ],
        ),
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "nghttp2_jll", uuid = nghttp2_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid, CompilerSupportLibraries_jll_uuid]),
            version_ranges = [
                (v"1.13.0", v"1.14.0") => v"1.67.1+0",
            ],
        ),
    ],
    p7zip_jll_uuid => [
        StdlibSegment(
            base_info = StdlibBaseInfo(name = "p7zip_jll", uuid = p7zip_jll_uuid, deps = UUID[Artifacts_uuid, Libdl_uuid]),
            version_ranges = [
                (v"1.6.0", v"1.6.6") => v"16.2.1+0",
                (v"1.6.7", v"1.6.7") => v"17.4.0+0",
                (v"1.7.0", v"1.7.3") => v"16.2.1+1",
                (v"1.8.0", v"1.9.4") => v"17.4.0+0",
                (v"1.10.0", v"1.11.5") => v"17.4.0+2",
                (v"1.12.0", v"1.12.1") => v"17.5.0+2",
                (v"1.13.0", v"1.14.0") => v"17.6.0+0",
            ],
        ),
    ]
)

# Next, we also embed a list of stdlibs that must _always_ be treated as stdlibs,
# because they cannot be resolved in the registry; they have only ever existed within
# the Julia stdlib source tree, and because of that, trying to resolve them will fail.
const UNREGISTERED_STDLIBS = Dict{UUID, StdlibInfo}(
    Base64_uuid => StdlibInfo(
        "Base64",
        Base64_uuid,
        nothing,
        UUID[],
        UUID[],
    ),
    CRC32c_uuid => StdlibInfo(
        "CRC32c",
        CRC32c_uuid,
        nothing,
        UUID[],
        UUID[],
    ),
    Dates_uuid => StdlibInfo(
        "Dates",
        Dates_uuid,
        nothing,
        UUID[Printf_uuid],
        UUID[],
    ),
    Distributed_uuid => StdlibInfo(
        "Distributed",
        Distributed_uuid,
        nothing,
        UUID[Sockets_uuid, Random_uuid, Serialization_uuid],
        UUID[],
    ),
    FileWatching_uuid => StdlibInfo(
        "FileWatching",
        FileWatching_uuid,
        nothing,
        UUID[],
        UUID[],
    ),
    Future_uuid => StdlibInfo(
        "Future",
        Future_uuid,
        nothing,
        UUID[Random_uuid],
        UUID[],
    ),
    InteractiveUtils_uuid => StdlibInfo(
        "InteractiveUtils",
        InteractiveUtils_uuid,
        nothing,
        UUID[Markdown_uuid],
        UUID[],
    ),
    LibGit2_uuid => StdlibInfo(
        "LibGit2",
        LibGit2_uuid,
        nothing,
        UUID[],
        UUID[],
    ),
    Libdl_uuid => StdlibInfo(
        "Libdl",
        Libdl_uuid,
        nothing,
        UUID[],
        UUID[],
    ),
    LinearAlgebra_uuid => StdlibInfo(
        "LinearAlgebra",
        LinearAlgebra_uuid,
        nothing,
        UUID[Libdl_uuid],
        UUID[],
    ),
    Logging_uuid => StdlibInfo(
        "Logging",
        Logging_uuid,
        nothing,
        UUID[],
        UUID[],
    ),
    Markdown_uuid => StdlibInfo(
        "Markdown",
        Markdown_uuid,
        nothing,
        UUID[Base64_uuid],
        UUID[],
    ),
    Mmap_uuid => StdlibInfo(
        "Mmap",
        Mmap_uuid,
        nothing,
        UUID[],
        UUID[],
    ),
    Pkg_uuid => StdlibInfo(
        "Pkg",
        Pkg_uuid,
        v"1.1.3",
        UUID[REPL_uuid, LibGit2_uuid, Random_uuid, Dates_uuid, UUIDs_uuid, Markdown_uuid, Printf_uuid, SHA_uuid],
        UUID[],
    ),
    Printf_uuid => StdlibInfo(
        "Printf",
        Printf_uuid,
        nothing,
        UUID[Unicode_uuid],
        UUID[],
    ),
    Profile_uuid => StdlibInfo(
        "Profile",
        Profile_uuid,
        nothing,
        UUID[Printf_uuid],
        UUID[],
    ),
    REPL_uuid => StdlibInfo(
        "REPL",
        REPL_uuid,
        nothing,
        UUID[Sockets_uuid, InteractiveUtils_uuid, Markdown_uuid],
        UUID[],
    ),
    Random_uuid => StdlibInfo(
        "Random",
        Random_uuid,
        nothing,
        UUID[Serialization_uuid],
        UUID[],
    ),
    Serialization_uuid => StdlibInfo(
        "Serialization",
        Serialization_uuid,
        nothing,
        UUID[],
        UUID[],
    ),
    SharedArrays_uuid => StdlibInfo(
        "SharedArrays",
        SharedArrays_uuid,
        nothing,
        UUID[Distributed_uuid, Random_uuid, Serialization_uuid, Mmap_uuid],
        UUID[],
    ),
    Sockets_uuid => StdlibInfo(
        "Sockets",
        Sockets_uuid,
        nothing,
        UUID[],
        UUID[],
    ),
    SparseArrays_uuid => StdlibInfo(
        "SparseArrays",
        SparseArrays_uuid,
        nothing,
        UUID[LinearAlgebra_uuid, Random_uuid],
        UUID[],
    ),
    SuiteSparse_uuid => StdlibInfo(
        "SuiteSparse",
        SuiteSparse_uuid,
        nothing,
        UUID[SparseArrays_uuid, LinearAlgebra_uuid, Libdl_uuid],
        UUID[],
    ),
    Test_uuid => StdlibInfo(
        "Test",
        Test_uuid,
        nothing,
        UUID[Logging_uuid, Distributed_uuid, Random_uuid, InteractiveUtils_uuid],
        UUID[],
    ),
    UUIDs_uuid => StdlibInfo(
        "UUIDs",
        UUIDs_uuid,
        nothing,
        UUID[Random_uuid, SHA_uuid],
        UUID[],
    ),
    Unicode_uuid => StdlibInfo(
        "Unicode",
        Unicode_uuid,
        nothing,
        UUID[],
        UUID[],
    )
)
