name: Check Historical Stdlib Generator
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  check_hsg:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          # version: '1'
          version: 'nightly'
      - run: julia --color=yes .ci/check_hsg.jl
